# Generated by Django 5.2.7 on 2025-11-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagecontactus",
            name="read",
            field=models.BooleanField(default=False),
        ),
    ]
