# Generated by Django 5.2.7 on 2025-11-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post_app", "0002_messagecontactus_read"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/articles"),
        ),
    ]
